version: "2"
services:
  postgres:
    image: postgres:16.3-bookworm
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: mpsdigital
      POSTGRES_PASSWORD: trustno1
  mpsdigital:
    image: node:22.2-bookworm
    restart: always
    user: mpsdigital
    working_dir: /home/mpsdigital/app
    environment:
      NODE_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_USER: mpsdigital
      POSTGRES_PASSWORD: trustno1
    volumes:
      - ./:/home/mpsdigital/app
    ports:
      - 443:443
    command:
      - npm install yarn && yarn build --cwd frontend && npm install && npm start
