version: "2"
services:
  postgres:
    image: postgres:16.3-bookworm
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: mpsdigital
      POSTGRES_PASSWORD: trustno1
  mpsdigital:
    build: .
    restart: always
    user: node
    environment:
      NODE_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_USER: mpsdigital
      POSTGRES_PASSWORD: trustno1
    depends_on:
      - postgres
    ports:
      - 443:443
      - 80:80
